packages:
  - name: bot
    functions:
      - name: bot
        runtime: 'python:3.11'
        triggers:
        - name: hourly-rate
          sourceType: scheduler
          sourceDetails:
            cron: "0 * * * *"